name: My Workflow

on: [push]

jobs:
  my-job:
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: node js/test.js